name: Destroy
on:
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

env:
  REPOSITORY_NAME: graph-rs-repository

jobs:
  destroy:
    name: Destroy
    concurrency: deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::575737149124:role/graph-rs-deploy
        aws-region: us-east-1
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.2
    - name: Terraform
      run: |
        terraform init
        terraform fmt -check
        terraform plan -input=false -destroy \
          -var "git_commit_sha=${{github.sha}}" \
          -var "ecr_repository_name=$REPOSITORY_NAME" 
      working-directory: ./terraform
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false -destroy -var "git_commit_sha=${{github.sha}}" -var "ecr_repository_name=$REPOSITORY_NAME"
      working-directory: ./terraform